export const CHANGE_SEGMENT_COIN_INDEX = "CHANGE_SEGMENT_COIN_INDEX"
export const CHANGE_SEGMENT_ICO_INDEX = "CHANGE_SEGMENT_ICO_INDEX"

// MarketCap API Request
export const MARKETCAP_REQUEST_LOADING = "MARKETCAP_REQUEST_LOADING"
export const MARKETCAP_REQUEST_SUCCESS = "MARKETCAP_REQUEST_SUCCESS"
export const MARKETCAP_REQUEST_ERROR = "MARKETCAP_REQUEST_ERROR"

//CoinList API Request
export const COIN_REQUEST_LOADING = "COIN_REQUEST_LOADING"
export const COIN_REQUEST_SUCCESS = "COIN_REQUEST_SUCCESS"
export const COIN_REQUEST_ERROR = "COIN_REQUEST_ERROR"