export const CHANGE_SEGMENT_COIN_INDEX = "CHANGE_SEGMENT_COIN_INDEX"
export const CHANGE_SEGMENT_ICO_INDEX = "CHANGE_SEGMENT_ICO_INDEX"

// MarketCap API Request
export const MARKETCAP_REQUEST_LOADING = "MARKETCAP_REQUEST_LOADING"
export const MARKETCAP_REQUEST_SUCCESS = "MARKETCAP_REQUEST_SUCCESS"
export const MARKETCAP_REQUEST_ERROR = "MARKETCAP_REQUEST_ERROR"

//Top100Coin API Request
export const COIN_REQUEST_LOADING = "COIN_REQUEST_LOADING"
export const COIN_REQUEST_SUCCESS = "COIN_REQUEST_SUCCESS"
export const COIN_REQUEST_ERROR = "COIN_REQUEST_ERROR"

//AllCoin API Request
export const ALL_COIN_REQUEST_LOADING = "ALL_COIN_REQUEST_LOADING"
export const ALL_COIN_REQUEST_SUCCESS = "ALL_COIN_REQUEST_SUCCESS"
export const ALL_COIN_REQUEST_ERROR = "ALL_COIN_REQUEST_ERROR"

//Live ICO API Request
export const LIVE_ICO_REQUEST_LOADING = "LIVE_ICO_REQUEST_LOADING"
export const LIVE_ICO_REQUEST_SUCCESS = "LIVE_ICO_REQUEST_SUCCESS"
export const LIVE_ICO_REQUEST_ERROR = "LIVE_ICO_REQUEST_ERROR"

//Upcoming ICO API Request
export const UP_ICO_REQUEST_LOADING = "UP_ICO_REQUEST_LOADING"
export const UP_ICO_REQUEST_SUCCESS = "UP_ICO_REQUEST_SUCCESS"
export const UP_ICO_REQUEST_ERROR = "UP_ICO_REQUEST_ERROR"

//Finished ICO API Request
export const FINISHED_ICO_REQUEST_LOADING = "FINISHED_ICO_REQUEST_LOADING"
export const FINISHED_ICO_REQUEST_SUCCESS = "FINISHED_ICO_REQUEST_SUCCESS"
export const FINISHED_ICO_REQUEST_ERROR = "FINISHED_ICO_REQUEST_ERROR"